### ISSUE TITLE
Revise nuclar CO2 equivalent? Take in account mining, decommissioning, ...

### ISSUE THREAD

**Issue by jmgarnier** [tmrowco/electricitymap#1008]
Hello,

Very nice dataviz project. Thank you :)

I am surprised by:
https://github.com/tmrowco/electricitymap/blob/5d280d6816550c19115ed76c10f9bdc2a54de95d/config/co2eq_parameters.js#L32-L47

Solar has a higher factor than nuclear !?! I once saw a documentary which calculated that nuclear was close to gas plants (which is 490 in your data). Nuclear can be a very religious subject but if you are ready to hear some experts on the subject, I can recommend some people / sources.

For example, uranium mining is a very carbon intensive activity so is uranium enrichment (not talking about health impact on locals). Also, if decommissioning  emissions were included, emissions would sky rocket.

Finally, the cost of an accident - not talking about money or people life and health - is very carbon intensive. With aging reactors and fake security certificates (example: France or South Korea), this should somehow be taken in account to be fair with energies which come from the sun and resist to tsunami and earthquakes ...

**Comment by brunolajoie** [comment]
Thanks a lot for your input.
The values you see here are median values from the IPCC 2014 report, which gather all peer-reviewed paper on that matter. IPCC is the most trusted scientific body on climate change. However, these data are only median values and hides large discrepancies between type and age of nuclear power plants (as well as solar PV). We are trying to refine these estimate by country to better account for these variability in #738. Feel free to contribute! Thanks a lot

![image](https://user-images.githubusercontent.com/22095643/35000546-fdbea85e-fae4-11e7-9033-c2b63f80dcf7.png)

**Comment by corradio** [comment]
@brunolajoie does it explicitely take into account decomissioning? If yes, I think it's worth adding to the FAQ in the README.

**Comment by brunolajoie** [comment]
Yes it does. Will add!

**Comment by brunolajoie** [comment]
Actually, it's already written in the readme ```The carbon intensity of each type of power plant takes into account emissions arising from the whole lifecycle of the plant (construction, fuel production, operational emissions, and decommissioning).```

**Comment by corradio** [comment]
Great. Let's also add it to the FAQ to make it very clear.
@jmgarnier I guess this answers your question?

**Comment by jmgarnier** [comment]
As I am still surprised by the numbers for nuclear and solar, I have pinged [2 specialists on twitter](https://twitter.com/jmgarnier_/status/959849060579540994) - including one engineer who has worked in the nuclear industry - about "IPCC 2014" numbers. They may come up with other sources, maybe more recent or more accurate (!).

I don't think this is intentional but you make 🇫🇷 look super green versus countries who invest much more in renewable energies (🇵🇹 , 🇩🇰, 🇩🇪 , 🇪🇸 , ...) but still have dirty coal plants. On the other hand, unrelated to this issue, [uranium enrichment and mining is not very human and environmental friendly](https://vimeo.com/8547737) 😭 

But thanks for taking the time to check and reply 👍

**Comment by corradio** [comment]
Yes indeed we only look at carbon here but there's a lot of other
environmental factors that could be taken into account.
Let us know what the response will be!
Olivier

**Comment by jmgarnier** [comment]
On the follow up for this issue, I think you should have a settings with a  slider to adjust CO2eq for each kind of energy. electricitymap.org is being used as an argument agains renewable energies 😭 

I am not sure this what you wanted to happen when starting this business .... Man made climate change is getting worst alarmingly fast 😨. Renewables are part of the solution ... I hope!

**Comment by jarek** [comment]
> I think you should have a settings with a slider to adjust CO2eq for each kind of energy.

Create your own reality?

Even with nuclear at 110 gCO2eq-lifecycle/kWh, French electricity would be, in this year, more climate-friendly than Germany's. Anything else would be guessing the future.

(IMHO)

**Comment by brunolajoie** [comment]
Hello @jmgarnier ! Thanks for contacting us!

Rest assure, values for nuclear are currently already including all lifecycle-related emissions! The fact is, that compared to the amount of kWh produced over the lifetime of the plant, CO2 emissions are extremely low. We use IPCC median, but when I look at professional databses such as Ecoinvent, figures are very similar. 

We only focus on greenhouse gas though! Indeed, nuclear waste is a non-climate related problem of importance! 

Our improvement goal is to find more country-specific GHG emission factors per type of power plant. So that an old gas plant in russia will be more polluting than a brand new one in the UK. ref #738 



We know well that IPCC values are not perfect, far from it (Let's remind ourself that the IPCC median value we use for coal is only 820gCO2eq/kWh, which is, to my point of view, very low! Basically, wherever I look in more detail (ecoinvent, etc..) I often see values above 1000gCO2eq/kWh!)

**Comment by jmgarnier** [comment]
@jarek 
> Create your own reality?

Not sure what you are trying to achieve with this kind of gut reaction. If you were standing in front of me, I am not sure you would react the same way. Especially with someone you don't know.

The reality is that CO2eq is a complex number to calculate and electricitymap model simplifies the problem by using one number instead of a range => https://www.researchgate.net/publication/222396555_Greenhouse-gas_emissions_from_solar_electric-_and_nuclear_power_A_life-cycle_study

For example, according to them, Nuclear varies from 3 to 110g CO2eq/kWh. electricitymap model has picked 12 CO2eq/kWh.

By adding a settings feature to specify a range for each type of energy per country or geographical area, I believe it would make the map closer to reality.

**Comment by brunolajoie** [comment]
To repeat myself, 
- 12g is IPCC median value, we did not "cherry pick" it.
- But still, I have analysed the very reputable ecoinventv3 database, and for a country like France, for instance, LCA emission intensity values are (in gCO2eq/kWh)
 

  | value_infrastructure | value_operation | value_total
-- | -- | -- | --
electricity production, nuclear, pressure   water reactor | 2.2684 | 10.6401 | 12.9086
electricity production, wind, >3MW   turbine, onshore | 24.7879 | 0.1332 | 24.9210

So, we're not that far from the truth.

**Comment by jmgarnier** [comment]
@brunolajoie You no longer work for electricitymap so I am not replying to you personally. However, you seemed to have been annoyed by my last comment ( "To repeat myself") so I will apologize if I did offend you.

> So, IPCC global average medial values are not far from the truth, at least for a west-european country like France

I am not a scientist but the static definition of  "the truth" makes me ask 2 questions:

On one hand, by using the same gCO2eq/kWh values in every country, electricity map model simplifies things. It's OK, it's just an abstraction. There are no number per country and I guess you don't want to end up with a crazy model. But people keep using screenshots and they just love the green of France and boo the brown of Germany (especially French pro nuclear people and journalists!). Maybe you could add a note or a blog post about your simple model?

On the other hand, I am struggling with the fact that gCO2eq/kWh for nuclear plants or renewable does not change over time (same number as 2014!). This is rather complex, and technologies are changing, The emissions impact of mining of uranium in Niger, Australia, Kazakhstan might be under estimated? (example: presence of French army in Niger). Do we take in account for the LCA the emissions to decommission plants in the next century and to store the waste (and any impact it can have).

And especially in the case of ageing reactors and rapid climate changes. Nuclear power plants do not work well during extreme events (heat waves or flooding). ASN just revealed that diesel generators in EDF plants in 🇫🇷do not work well in heat waves. Moreover, in the context of a global pandemic and remote ASN controls, the risk of accidents is rising. 

Will electricitymap increases the  gCO2eq/kWh for Nuclear if a new accident happens?
Cleaning up the mess takes a lot of energy  ...

**Comment by jarek** [comment]
@jmgarnier, if you have better gCO2eq/kWh numbers that are peer reviewed, please do post them. Otherwise it'll just be going in circles here.

IPCC numbers are used as baseline to prevent people from cherry-picking their favourite numbers or using non-numerical arguments. Similarly to your arguments "please show nuclear as bad because we want to boost renewable energy and an accident could happen" people could be posting "please show wind as bad because grid stability and duck curve".

> And especially in the case of ageing reactors and rapid climate changes. Nuclear power plants do not work well during extreme events (heat waves or flooding).

In a sense that would substantially change their gCO2eq/kWh performance?

> Moreover, in the context of a global pandemic and remote ASN controls, the risk of accidents is rising.

This seems to me to be fear-mongering. In principle it's no different from people who warn against wind energy because a failed turbine once started a forest fire somewhere. Unless you have a peer-reviewed figure on the risk or likelihood of accident.

**Comment by brunolajoie** [comment]
Thanks for your comment @jmgarnier ! Never a bad thing to discuss.

- "Why gCO2eq/kWh for nuclear plants or renewable does not change over time (same number as 2014!)" : because the average power plant fleet does not evolve rapidly at all (reactors lasts 40 to 80 years)

- "The emissions impact of mining of uranium in Niger, Australia, Kazakhstan might be under estimated?" They might be, or they might not be, how do you know? We don't. That's why we need to rely on peer-reviewed scientific papers.

- "Do we take in account for the LCA the emissions to decommission plants in the next century and to store the waste" --> yes. That's called "lifecycle analysis" emission factors. That's why also wind and solar and hydro are not stricly speaking 0 emission.

- About Nuclear risks: Accident and risks are not measurable in gCO2eq/kWh. You may measure them in gU/kWh for instance. But then, how would you display in **a single color scale** CO2-emission/kWh + Nuclear risks + Water consupmtion/kWh + Land-used m2/kWh? etc... You would need multiple electricityMap.

**Comment by archie-bal** [comment]
@brunolajoie at least [in this paper, from Stanford University (2009)](https://www.scopus.com/record/display.uri?eid=2-s2.0-65649109694&origin=inward&txGid=a49ee7042b8b10ebd084039a182cf5c9&featureToggles=FEATURE_NEW_DOC_DETAILS_EXPORT:1), you get much higher values for GHG-emissions of current nuclear reactors.
He referenced opportunity cost emissions for nuclear power of 59–106 g CO2 /kWhe in addition to the CO2 costs from the nuclear lifecycle of **9–70**. In total he stated for nuclear energy costs of **68–180 g CO2 /kWhe**.

So, your calculation basis of electricityMap, the median of 12 g CO2/kWhe is way off, by now.

**Comment by jmgarnier** [comment]
Same for 🌞 , in https://github.com/electricitymaps/electricitymaps-contrib/blob/master/config/co2eq_parameters_lifecycle.json#L131-L134 it still says 45 

```json
      "solar": {
        "source": "IPCC 2014",
        "value": 45
      },
```

It's time to update the data! The value has changed
