### ISSUE TITLE
Split NO and DK into bidding zones

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1069]
Requires #917, but could be great to start adding granularity!

**Comment by tmslaine** [comment]
Different organizations have a bit different maps of NO bidding zones.
ENTSOE:
![entsoe-nordic](https://user-images.githubusercontent.com/25774514/36350124-d09bb75c-149a-11e8-8b28-f27cd3d09e38.png)
Norwegian TSO Statnett:
![statnett](https://user-images.githubusercontent.com/25774514/36350127-de7de412-149a-11e8-8735-4479650aee52.png)
Norwegian Water Resources and Energy Directorate NVE:
![nve-norway](https://user-images.githubusercontent.com/25774514/36350143-4beca786-149b-11e8-92ae-eef9352c8953.png)
I assume NVE has the most up-to-date map out of these ones, freehand-polygons from their map combined with ne10m_cultural gives:
![image](https://user-images.githubusercontent.com/25774514/36350180-61e58200-149c-11e8-9590-ab35abcc2a62.png)

For Denmark there is no such controversy. The ENTSOE map above agrees with what the TSO energinet shows, i.e. split on the Stor-Baelt bridge:
![energinet-dk](https://user-images.githubusercontent.com/25774514/36350287-cba1f1a4-149e-11e8-8fa2-520b8e5636a4.png)
This split also agrees with administrative zones, giving DK1 = Nordjylland, Midtjylland, Syddanmark and DK2 = Hovedstaden, Sjaelland
As Bornholm is already included as a separate zone, Bornholm can be excluded from DK2. The price should however be the same on "mainland" DK2 and Bornholm.
Again matching with ne_10m gives:
![image](https://user-images.githubusercontent.com/25774514/36350350-be908f56-149f-11e8-82c2-478948fd4ad6.png)

**Comment by corradio** [comment]
I've started a branch at https://github.com/tmrowco/electricitymap/tree/olc/add-dk1-dk2 but I have some troubles excluding Bornholm (which is a subunit) from Sjælland (which is a state).

**Comment by corradio** [comment]
I managed to split the geometries correctly. Can anyone help with installed capacities for DK1 / DK2?

**Comment by alixunderplatz** [comment]
@corradio I'll take a look at capacities!

**Comment by alixunderplatz** [comment]
This is **from ENTSO-E**, where numbers for 2016 and 2017 are exactly the same. So maybe not the most recent ones, but at least split by zones.

**For DK1:**
'capacity': {
            'biomass': 326,
            'coal': 2775,
            'gas': 1700,
            'oil': 292,
            'hydro': 9,
            'solar': 421,
            'wind': 3809
        },

**For DK2:**
'capacity': {
            'biomass': 234,
            'coal': 2072,
            'gas': 1241,
            'oil': 759,
            'solar': 180,
            'wind': 1036
        },

Since these data are a bit old and don't seem to have been updated through 2017, there may be deviations. For wind energy, there are about 600 MW missing compared to the latest numbers from windeurope - unfortunately, th numbers are not split to the DK zones in their report. 
That's it for the moment. Maybe I can find something on Energinet's site that shows recent numbers. energidataservice.dk doesn't seem to have data for installed generation capacity yet.
Will keep looking for better ones!

**Comment by tmslaine** [comment]
Danish Energy Agency maintains a master data register of wind turbines bigger than 6kW:
https://ens.dk/en/our-services/statistics-data-key-figures-and-energy-maps/overview-energy-sector

The turbines are listed by municipality. The municipalities can then be mapped to administrative zones using for example https://en.wikipedia.org/wiki/List_of_municipalities_of_Denmark.

**Comment by alixunderplatz** [comment]
@tmslaine Cool! Does it also include offshore?

@corradio I think the easiest and safest way to get all the data is to contact Energinet.dk, that stuff is kind of hard to find. I could find some

______________

The only things I can come up with for the DK1 and DK2 zones are these central power plant numbers from a Energinet.dk presentation for 2016, which need to be mapped to their type:
![image](https://user-images.githubusercontent.com/25743609/36743351-6612c3f6-1bea-11e8-83ed-8b17ede66e61.png)
![image](https://user-images.githubusercontent.com/25743609/36743454-a0288f1c-1bea-11e8-811f-21490d76b60e.png)

plus some decentral stuff:
![image](https://user-images.githubusercontent.com/25743609/36743570-decef7b0-1bea-11e8-9221-901f14b3c1cd.png)

____________

Here is a table with capacities [from a report of 2017](https://energinet.dk/Om-publikationer/Publikationer/Halvaarsrapport-2017) for _entire Denmark_, if there is a desire to improve the numbers used in the electricitymap at the moment.

![image](https://user-images.githubusercontent.com/25743609/36744190-76cd0588-1bec-11e8-8b83-fb8cdeb56844.png)

I think the final yearly report of energinet will be published soon in March, which is going to contain most recent stuff for 2017 for denmark as a whole at least.

⚠️⚠️⚠️ **PLEASE NOTE: This chart has conflicts with the generation data!!!** ⚠️⚠️⚠️

According to the table, and if I understand the table correctly and am not missing something crucial, some coal capacity seems to be fired with biomass now (capacity 615 MW moved from coal to biomass), leaving Denmark with 1.6 GW of installed coal capacity. And Biomass capacity is way bigger than what is currently reported to ENTSO-E. 
Can this be true??? Data on ENTSO-E says there were up to 2.4 GW of coal today. 

@corradio @brunolajoie I have the feeling, the reported data on ENTSO-E for Denmark is kind of not correct!
Seems like they are missing something or are reporting some biomass as coal or gas. Maybe this is why even at high wind, there still is coal in the chart for Denmark, because some converted coal plants are running on biomass/wood chips.

For example, the units in Avedør are firing biomass instead of coal ([according to this article](http://www.iwr.de/news.php?id=32730)) but on ENTSO-E they are shown as "fossil gas" (which might be a secondary fuel) ... ?!?!??!

![image](https://user-images.githubusercontent.com/25743609/36745159-f48a9308-1bee-11e8-87db-95c2eb815587.png)

I think this needs some deeper investigations! I remember people were like "uh Denmark is running on 100% wind but coal is still producing with ~800 MW ... why is that?!" 
This could be the hidden answer.

**Comment by tmslaine** [comment]
@alixunderplatz Yes, there is a distinction Land/Hav for Onshore/Offshore wind turbines in the Danish wind turbine register.

**Comment by brunolajoie** [comment]
@alixunderplatz thanks for spotting the coal/biomass issue, let's discuss it in your #1161  (but just to answer your last comment: when ppl said DK is 100% wind, they meant DK wind is producing as much as DK consumes. But you still had coal/biomass/gas or other plant running and therefore it never reached 100% wind in consumption-mix).

**Comment by corradio** [comment]
@fedders do you have information about installed capacity of coal/oil/biomass/wind/solar for DK1 and DK2? We're in the process of splitting DK1 and DK2 on the map and it would be nice to have the installed capacity broken down by production type!

**Comment by fedders** [comment]
There's at least the data on the Transparency portal. It doesn't seem to have been updated with 2018 figures yet.

- [DK1
](https://transparency.entsoe.eu/generation/r2/installedGenerationCapacityAggregation/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2016+00:00|UTC|YEAR&dateTime.endDateTime=01.01.2018+00:00|UTC|YEAR&area.values=CTY|10Y1001A1001A65H!BZN|10YDK-1--------W&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19)- [DK2](https://transparency.entsoe.eu/generation/r2/installedGenerationCapacityAggregation/show?name=&defaultValue=false&viewType=TABLE&areaType=BZN&atch=false&dateTime.dateTime=01.01.2016+00:00|UTC|YEAR&dateTime.endDateTime=01.01.2018+00:00|UTC|YEAR&area.values=CTY|10Y1001A1001A65H!BZN|10YDK-2--------M&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19)

**Comment by corradio** [comment]
PR submitted for DK.
For NO, the task now is to get the proper geometries.

**Comment by tmslaine** [comment]
GeoJSON for Norway obtained by drawing over the elspot area lines NVE map shows:
[NorwayBZN.geojson.gz](https://github.com/tmrowco/electricitymap/files/1778717/NorwayBZN.geojson.gz)

**Comment by corradio** [comment]
@tmslaine fancy starting to add the zone geometries to our system, and split NO?

**Comment by systemcatch** [comment]
We should add proper names for the new zones in locales and maybe add something to the faq about bidding zones as I think it's going to be a recurring question.

**Comment by corradio** [comment]
Closing this and replacing by #1381
