### ISSUE TITLE
Add Georgia (Country)

### ISSUE THREAD

**Issue by tmslaine** [tmrowco/electricitymap#1212]
Georgian State Electrosystem GSE has real-time production mix and exchange data on:
http://www.gse.com.ge/home
![georgia](https://user-images.githubusercontent.com/25774514/37414577-1f943cb0-27b2-11e8-9ded-5ca395b08519.png)

The dashboard pulls data from a json updated in http://www.gse.com.ge/apps/gsebackend/rest/map so writing a parser should be straightforward. For some reason exchange cable details are only shown when you access their web page via mobile.

The only issue with implementation is exchange inconsistency, as GSE regularly reports opposite GE->RU flow compared to http://br.so-ups.ru/Public/MainPage.aspx.

**Comment by systemcatch** [comment]
That looks good, I'm sure we can figure out what's going on with the exchange direction. Do you want to write this one @tmslaine ?

**Comment by alixunderplatz** [comment]
From the 2017-2027 [network development plan](http://www.gse.com.ge/communication/Publications/Ten-Year-Network-Development-Plan-of-Georgia) (550 pages 😮):
![image](https://user-images.githubusercontent.com/25743609/37475518-311cbdf6-2873-11e8-8708-9fa7ca4b09e6.png)

But it seems like coal has a significantly small share in installed capacity (2x 6.5 MW), so thermal could be entirely mapped to gas? All the other plants in that list are working on natural gas as main fuel. A new larger coal plant is under construction and will not come online before 2020 according to the TYNDP and [other sources](https://www.sourcewatch.org/index.php/Gardabani_power_station).

![image](https://user-images.githubusercontent.com/25743609/37476522-ae92d6d8-2875-11e8-9df2-a10776feb470.png)

IEA has [this in the generation statistics](https://www.iea.org/statistics/statisticssearch/report/?country=GEORGIA&product=electricityandheat&year=2015
) for 2015:

gas: 2379 GWh
hydro: 8454 GWh

So I think mapping thermal to gas is fine at the moment.
______ 

Looks like the exchange with Russia is stuck at 23 MW on that site? It kind of never changes. The "0 MW" exchanges in the upper left corner might be due to the political conflict in Abchasia (since 2008) 🤔.

**Comment by tmslaine** [comment]
I agree it is questionable if the exchanges with Russia can be trusted.
One or two of them lead to Abkhazia, the third one is located in South Ossetia.
Both Abkhazia and South Ossetia have claimed independence of Georgia so GSE possibly has no access to the GE->RU flows. It needs to be tested what happens if the parser returns None for GE->RU flow.

**Comment by systemcatch** [comment]
Parser is working well so far.
![georgia](https://user-images.githubusercontent.com/30196510/37559699-5e59be12-2a22-11e8-9a58-65def42aadf8.png)

**Comment by systemcatch** [comment]
Ok the GE is working fine so this can be closed.
