### ISSUE TITLE
Add static carbon intensity for NL exports

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#1277]

**Comment by corradio** [comment]
Talked to Dr. Martien Visser from Entrance (cc @alixunderplatz)
> To make it easy: the number for the last 12 months (April 2017 - March 2018) is 437 gr/kWh.
I think that's a number we can use!

**Comment by corradio** [comment]
It's domestic generation only, so indeed it is a very crude approximation. You are totally right.
How do you suggest we proceed? Correct it with the average flows and the intensities of neighbours?

**Comment by alixunderplatz** [comment]
That's really a tough question.
The only thing that seems possible at the moment is combining total generation [from TenneT](https://www.tennet.eu/nl/elektriciteitsmarkt/data-dashboard/productie/) (even though it is not always reliably available) with the static intensity and putting it to the "unknown" category. This way, at least the imports would have their influence on the average domestic carbon intensity. If it's possible, I suggest leaving NL in grey and only consider this "synthetic mix" for the export intensity.

![image](https://user-images.githubusercontent.com/25743609/38304144-aa34746e-3808-11e8-9759-0d95fbae9fff.png)

Unfortunately, the recent generation is displayed as "-" at the moment. Maybe that's a temporary issue.

![image](https://user-images.githubusercontent.com/25743609/38305122-fbd130c0-380b-11e8-9a36-17c047aa450a.png)

**Comment by PaulCornelissen** [comment]
Actually you don't have to put it all under "unknown" because renewables production is available from:
http://energieopwek.nl

Separated in biomass, wind and solar.

**Comment by alixunderplatz** [comment]
@PaulCornelissen yeah, that site had also been mentioned in the main issue #78.

As far as I can recall, these figures are estimates and would "spoil" the mix with the static carbon intensity in return, because they are already included in that static value that is mentioned above.
In addition, in the biogas category, they only seem to consider generation from biogas and not from other biomass like wood chips (I think there were projects to use wood chips as fuel in coal power plants, similar to Denmark?!) or waste.

**Comment by brunolajoie** [comment]
A more detailed answer from Dr. Visser on the 2017 annual NL average production (MWh) is: 
> 30% coal, 20% cogeneration (gas) and 28% gas-fired, renewables (14%), coke-over gas (5%), nuclear (4%).
