### ISSUE TITLE
Create a build script for running locally

### ISSUE THREAD

**Issue by systemcatch** [tmrowco/electricitymap#1278]
When developing locally it would good to build the map from a script rather than having to enter `docker-compose run --rm web npm run watch` then start a new terminal and run `docker-compose up --build`

Something like `./build.sh`

This is just a 'nice to have' thing. I know there are more important things to work on right now.

**Comment by corradio** [comment]
@systemcatch I don't really see a good way to do this TBH.
We can't get rid of docker because it injects lot of things through the node server (e.g. translations).
you can actually just build by doing `docker-compose build`, but the watch script is required if you want to see live updates when you dev in JS.

**Comment by corradio** [comment]
OK I understand.
The proper way to do it would be to merge the system that does the compilation and the system that serves the file (HTTPServer).
Right now both can't be decoupled, but else a webpack dev server would be perfect for this.
Unfortunately this means we have to run two commands.
We could add another dependency (like `foreman`) that runs the two commands at the same time, but this is not recommended in the docker guidelines (one command for one container), and I think it's also overkill.

**Comment by systemcatch** [comment]
Given that this would be a lot more work than I expected and we've got more pressing stuff to focus on atm I'll close this.
