### ISSUE TITLE
Add price to Turkey

### ISSUE THREAD

**Issue by jzlcdh** [tmrowco/electricitymap#1316]
I am not sure which of the ticker [prices](https://www.epias.com.tr/en) to use but section 6.7.3 BLOCK ORDER BOOK in [this guide](https://www.epias.com.tr/wp-content/uploads/2017/06/INTRADAY_MARKET_USER_GUIDE_ENG_18.09.2017.pdf) may help.

**Comment by systemcatch** [comment]
What do the 3 ticker price headings translate to?

**Comment by alixunderplatz** [comment]
@jzlcdh I just scrolled down a little bit on that side and found this chart

![image](https://user-images.githubusercontent.com/25743609/38495869-9501d608-3bfb-11e8-95d8-dfd257d929f1.png)

which is using the "PTF" for the day-ahead market price.


The market operator also has a large Transparency platform 👍 
I could find a section for the day-ahead market, which is safer to use because you can set the desired date:

https://seffaflik.epias.com.tr/transparency/piyasalar/gop/ptf.xhtml

![image](https://user-images.githubusercontent.com/25743609/38496210-eb7f4e88-3bfc-11e8-9c2b-2a44ae205b04.png)

**Comment by systemcatch** [comment]
There is also the option to scrape the data from the html directly.

**Comment by jzlcdh** [comment]
Sorry I haven't time to do this. How do I unassign myself from this issue?
