### ISSUE TITLE
g co2 / kWh for oil.

### ISSUE THREAD

**Issue by duckland2000** [tmrowco/electricitymap#1357]
You are using a very strange number for the amount of co2/kWh for oil. I'm looking at Estonia and the number is extremely high, much higher than the reality.

Oil is between natural gas and coal. Generally it's natural gas ~600 g co2/kWh, oil ~800 g co2/kWh and coal ~1000 g co2 /kWh.

You have something like 1500 g co2 / kWh.

You can find many sources, you have used IPCC for others. So this one for example: https://www.ipcc.ch/pdf/special-reports/sroc/Tables/t0305.pdf
Shows what I'm saying.

Please change the number for oil to a correct one. Or at least look into it and double and triple check your sources and make sure that they are accurate. :P ¨

Take care! //Micke

**Comment by alixunderplatz** [comment]
Hi @duckland2000!
Estonia is a special case: The country has large resources of "unconventional" oil shale, which are used for electricity generation. That's why the "oil" category in Estonia has a country-specific emission factor of 1515 gCO2eq/kWh. See the previous issue #278 for the discussion on Estonian oil shale and sources for that figure.

For all the other countries, 650 gCO2eq/kWh is used for generation from oil.

**Comment by maxbellec** [comment]
feel free to re-open @duckland2000 if the answer is not satisfactory
