### ISSUE TITLE
"available" not right word in "emissions available" 

### ISSUE THREAD

**Issue by jzlcdh** [tmrowco/electricitymap#1382]
After clicking the "carbon intensity" link and hovering over a bar there is a reference to "emissions available", which is not the best phrasing. Can't think of the best wording yet but feel free to assign this to me and I will get round to it eventually ("God willing" as my wife would make me say).

**Comment by corradio** [comment]
I agree. This might be a duplicate of https://github.com/tmrowco/electricitymap/issues/1375.

**Comment by jzlcdh** [comment]
Looks very similar but probably not duplicate as probably a different string when I find it.

**Comment by corradio** [comment]
@jzlcdh feel free to move forward with this!

**Comment by brunolajoie** [comment]
We could say, instead of 
>" 76% of emissions in Germany comes from coal"

the following fix:

>" 76% of carbon emissions related to electricity consumed in Germany comes from coal"

**Comment by corradio** [comment]
It's actually not "consumed" because at this point the exports (and storage) haven't been subtracted yet. The proper technical phrasing would be

> X % of emissions from electricity available in Germany comes from coal

i.e. just adding "from electricity".

**Comment by brunolajoie** [comment]
Oh, right, indeed!

**Comment by jzlcdh** [comment]
Sorry I had forgotten about this - I hope to do it in next few days.

**Comment by jzlcdh** [comment]
So just to be clear if electricity is generated in country Y but consumed in country Z are we assigning the emissions to Y or Z?

**Comment by jzlcdh** [comment]
Duh sorry yes it is obvious on the readme. So as a native speaker but not a professional writer the best I can come up with is:

"Coal emitted X% of greenhouse gases due to electricity being used now in Z"

I have created pull request #1457. So would it be easy for me to test the change (I have a windows 10 desktop) or does someone else do that when batching up several minor changes?

**Comment by brunolajoie** [comment]
I'm sorry to insist, but your suggestion is not correct strictly speaking. The exact definition is
"X % of emissions from electricity produced or imported in Germany comes from coal"

**Comment by brunolajoie** [comment]
The resulting carbon intensity will be computed as the scalar product of each of these percentages (for all type of fuels, and all imports), multiplied by the carbon intensity of each type of fuel and each type of imports. It will represent the carbon intensity of electricity consumed in Germany.

**Comment by jzlcdh** [comment]
@brunolajoie I understand and agree with your last comment and I think that is in accord with my suggestion.

If you think it is not please could you tell me where is the code which calculates the percentage? As I don't understand your comment before last and looking at the code might help.

**Comment by jarek** [comment]
That exact text is quite long and also requires introducing a new form of country name ("German"). Considering how much trouble we're having with this phrasing, and that the hovers only really work well on desktop (what is the % of desktop use?), would it perhaps be simpler and just as well to remove the hovers from "carbon emissions" subsection altogether and explain the figures in readme/FAQ?

**Comment by jzlcdh** [comment]
Good points @jarek - I will try and write wording without a new form of country name and which would suit both the hover tip and the FAQ. If that is not possible I will write a short one for the hover tip and a longer for the FAQ. But first could someone could let me know where the code is which calculates the percentage so I can look at it make sure I understand properly myself?

**Comment by brunolajoie** [comment]
@corradio proposal:
> X % of emissions from electricity available in Germany comes from coal

- "available" might remain consusing for people who really wants to understand what this % is about
- It's not "coal" but "local coal" that should be used to be exact
Overall, here's my suggestion
> 45 % of GHG emissions from electricity produced or imported in Germany comes from local coal

What do you think?

**Comment by jarek** [comment]
"electricity produced or imported in Germany" sounds a little awkward to me - "produced in or imported to Germany" would be more correct but no less awkward

"local coal" should probably be "local coal generation" else it sounds like it does not include any coal imported from abroad on a train and burned in Germany

As "45% of emissions" is plural, it should also be "come" not "comes"

If we want to be exact, perhaps we should also expand "GHG" to "greenhouse gases"

---

I suggested once to try to translate a string into other languages before adding it, so that we are sure of the meaning. I really encourage everyone to do this! How would you put it in French?

I notice that in Polish it's a bit different - we currently have "[region]: produkcja [type] tworzy [x]% emisji" which translates to "[region]: [type] production creates [x]% of emissions". In German we have "[x]% der CO2-Emissionen der Region [region] stammen aus [type]" which translates to "[x]% of CO2 emissions of [region] originate from [type]". However, neither specifies that the percentage is of emissions from electricity generation, and that the type is only local.

So how about:

* pl generation: "[region]: lokalna produkcja [type] tworzy [x]% z wszystkich emisji gazów cieplarnianych skutkujących z produkcji lub importu prądu"
  * rough translation: "[region]: local production of [type] creates [x]% of all greenhouse gas emissions caused by production or import of electricity"
* pl import: "[region]: import z [source] odpowiedzialny za [x]% emisji skutkujących z produkcji lub importu prądu"
  * rough translation: "[region]: import from [source] accounts for [x]% of all emissions caused by production or import of electricity"
* de: "[x]% der CO2-Emissionen der Region [region] stammen aus lokalen [type] Anlagen"
  * but I don't know how to specify "produced in or imported to" other than by going ridiculously long like "[x]% der CO2-Emissionen durch Erzeugung und Import von elektrischer Energie der Region..."
* en: "[x]% of GHG emissions due to electricity produced in or imported to [region] originate from local [type] generation"
* alternative en following the pl schema: "Local [type] generation creates [x]% of total greenhouse gas emissions due to production or import of electricity in [region]"
* en import: "Import from [source] accounts for [x]% of total greenhouse gas emissions due to production or import of electricity in [region]"

---

Or, like I suggested, remove the hovers altogether :P

**Comment by brunolajoie** [comment]
Hahahaha thanks for correcting my poor English grammar, at least we're all clearly aligned on the exact meaning of these now.
Its a matter of choice now, between simplicity and exactitude. I'm fine with all these, will let the community decides.
One last shot on my side (using oli's "available" and the distinction between local and imported)
> "[x]% of GHG emissions from electricity available for consumption in [region] originate from local [type] generation"
>"[x]% of GHG emissions from electricity available for consumption in [region] come from [region2] imports"

**Comment by jzlcdh** [comment]
Thanks for those comments - I now understand what was wrong with my previous pull request and have made the new one above. If I should test it myself please let me know (I have a windows desktop but have not done this kind of testing before).
