### ISSUE TITLE
Refine CO2 intensity figures by accounting for fixed vs. variable gCO2/kWh

### ISSUE THREAD

**Issue by brunolajoie** [tmrowco/electricitymap#237]
Currently, CO2 intensity figures by power plant (in gCO2eq/kWh) that we use are lifecycle emission factors, so that emission embedded in the manufacturing of the plant are taken into account. Therefore, we should not assign the value 0 to the CO2 intensity of a power plant that is not producing - instead one should divide lifecycle emissions figures between the operational part (related to fuel) and the manufacturing & installation part, in order to correct our real-time emissions figure accordingly.

Current lifecycle dataset does not differentiate Operational from Manufacturing emission intensity and comes from "IPCC Working Group III – Mitigation of Climate Change, Annex III: Technology - specific cost and performance parameters" (PDF). IPCC. 2014. p. 10. Retrieved 1 August 2014.

**Comment by ThierryOllivero** [comment]
I don't understand you point. We use gCO2eq/kWh, so if a plant is not producing, the value is 0. Since no kWh are produced. 

If we were counting gCO2eq/h or gCO2eq/y, then maybe we could say that idle plants are still emitting some CO2, but still it does not seem particularly true. 

The values we use from IPCC are a good compromise between showing only marginal (fuel) and showing total LCE. Unless you believe we should only show emissions for the operational part?

**Comment by brunolajoie** [comment]
After giving it a second thought, I think you are right. It seems a good compromise, which, anyway, might not change drastically the relative emission intensity of each countries.

**Comment by ThierryOllivero** [comment]
Should we keep the issue open then?

**Comment by tezellis** [comment]
> Unless you believe we should only show emissions for the operational part?

Is this something that has been considered? Having a marginal/LC toggle would allow users to decide (but maybe that is too confusing).

**Comment by corradio** [comment]
@brunolajoie is this still being considered? I recommend closing if we do not plan to work on this in the near future

**Comment by brunolajoie** [comment]
Not in the near future indeed!
