### ISSUE TITLE
Add country average pricing when zones are available

### ISSUE THREAD

**Issue by welph** [tmrowco/electricitymap#347]
Have you checked if http://www.nordpoolspot.com/ have an API which can be used for the nordic countries?

**Comment by nikkozzblu** [comment]
Nordic countries are actually also on ENTSOE, this is just that there is no such as «National» price. (same for Germany or Italy)

**Comment by welph** [comment]
You mean that for example in my country, Sweden. Is divided in 4 regions with different prices?

**Comment by corradio** [comment]
Exactly. We could show average prices for a country maybe?

**Comment by welph** [comment]
Either that or if it is possible, let the price change when you hover your mouse over different regions in a country that has different prices.

**Comment by corradio** [comment]
I'd like to keep country-level information for now. Averages should be possible.
Can you help?

**Comment by welph** [comment]
Sorry, no. I really would like to help. But knows very little when it comes to coding.
As I work at a powerplant in a pulpmill I find your project intresting :)
And yes we mostly burn biomass ;)

**Comment by fedders** [comment]
The Nordic region is split into multiple "[Market Balance Areas](https://emr.entsoe.eu/glossary/bin/view/ENTSO-E+Common+Glossary/Market+Balance+Area)", which should be represented in the map, as these are really the geographical boundaries, by which production, consumption and net-exchange can be determined.

I'd be happy to explain in further detail.

**Comment by corradio** [comment]
The real question is whether or not we wish to support sub-country data (see #196). It's more accurate, but most "non-experts" will find it confusing. I think we can make it work with some very thin boundaries between zones, and thick boundaries between countries. However, we'd need to find the polygons for each of the zones. If you can help, please comment on #196.

This issue is about whether or not we make a great mistake by taking the average price in order to show it at a country level.

**Comment by systemcatch** [comment]
@corradio is this issue still relevant now that we show state/bidding zone data?

**Comment by corradio** [comment]
Indeed let's close
