### ISSUE TITLE
Slow scrolling speed on mobile

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#348]
Home screen is slow to scroll on my iPhone 5S.
It seems to come from the flags when enough of them are visible on the screen (I tried removing the flags, which removes the lag, and I tried adding a lot of vertical space to only show a few of them on the screen, and it also removed the lag).
The flags are SVG so it might be painful to redraw?
@scarlac do you have an idea?

**Comment by scarlac** [comment]
Yeah, I tested it just now. Also seems slow on desktop safari in mobile emulation. Removed pretty much everything and still had FPS drops.
SVG seems to be the culprit (setting the background image to "none" for the flag-icon increases frame rate to 60 again).
I should generate static PNGs since (Mobile) Safari can't. Chrome seems unaffected.

**Comment by corradio** [comment]
Indeed that's what I thought. Is there a good workaround or should we
switch to a PNG library instead?

**Comment by scarlac** [comment]
Switching is the best. Workaround is to convert to PNGs.

**Comment by scarlac** [comment]
Potentials:
- https://www.flag-sprites.com
- http://icondrawer.com/flag-icons.php
- http://365icon.com/icon-styles/ethnic/classic2/

**Comment by corradio** [comment]
icondrawer is the only one we can use here, because it contains Northern Ireland (which is not included else). Downside is we have to pay. Upside is that its not expensive :)

**Comment by adamal** [comment]
I noticed each flag is it's own svg. Stack Overflow packages alle their things into [a single svg](https://cdn.sstatic.net/Sites/stackoverflow/img/sprites.svg?v=d689de80c4e2), and nudges it around with varying `background-position-x/y`. That might be worth trying.

**Comment by scarlac** [comment]
Maybe @adamal - I think using PNG would also work great. It's a tried-and-true method with no risk and still relatively low bandwidth usage.

**Comment by nikkozzblu** [comment]
Hi,

I believe the biggest room for improvement would come from playing with viewport and mobile native zoom/scroll.


Saying that because I tried couple of months ago the version on my mobile with option "show as computer" (chrome/android 6) and the rendering was working fine.


The only challenge is to catch the onScroll javascript event to adjust the "position:fixed" element like logo, and summary panel

Unfortunatly I can t see any coming availability for me to dedicate to trying this, but I can assist

________________________________
De : Seph Soliman <notifications@github.com>
Envoyé : samedi 25 mars 2017 11:03:44
À : tmrowco/electricitymap
Cc : Subscribed
Objet : Re: [tmrowco/electricitymap] Slow scrolling speed on mobile (#348)


Maybe @adamal<https://github.com/adamal> - I think using PNG would also work great. It's a tried-and-true method with no risk and still relatively low bandwidth usage.
