### ISSUE TITLE
Feature request: Toggle axis relative/absolute

### ISSUE THREAD

**Issue by b2000699** [tmrowco/electricitymap#453]
Hi,

currently the axis of the country info box is set to relative, i.e. the bar lengths of the various energy sources is always filling the entire width and the axis values change. So for example for the moment it looks like Finland (3GW) produces more nuclear energy than France (43GW).
This is good as it is for analyzing a particular country, but it would be nice to additionally be able to toggle this to absolute, so that someone can easily compare the countries absolute energy production by clicking through the countries. So someone could see with one glimpse that e.g. Germany produces a lot of energy and e.g. Denmark less.

Cheers

**Comment by corradio** [comment]
Hi @b2000699 ,

Unfortunately this won't work, as between e.g. Denmark and Germany, there's a 10x difference in scale size. On an absolute scale, you wouldn't be able to see what Denmark is producing.
Also the intent of the map is to show emission *intensities*, not absolute values. It's meant to understand what production mix, in a certain context, is able to have the lowest carbon electricity.
Absolute values on the other hand are harder to interpret, as they also depend on the size of the country. Is Germany a big polluter because it has a high intensity, or because it's a big country?
That's why we focus on intensities.

**Comment by b2000699** [comment]
Hi @corradio,

yes, that scale difference was what I was intending; in your example: To quickly see that Denmark is producing next to nothing compared to Germany. Of course, in this setting, someone could not understand the details of Denmark, sure. Therefore I proposed it as a toggle switch, so someone can easily switch from absolute to relative back and forth as he desires, depending on what he wants to analyze at that given moment.

@Carbon: Yes, as far as I understood also from another answer of you in another post, you are carbon-centric/ polution-centric with the app.
Of course this decision of yours is to be respected, but just to give you some feedback and food for thoughts: There are a lot of further uses of this great app! For instance right now your app is used in Greek forums to discuss the different levels of production of other European countries compared to Greece, where a heavy debate is going on pro/contra wind energy on some islands. What I want to say is: Maybe you want to think about moving away from the carbon/pollution-centric view on your app and move it more into a general purpose app for Energy analysis in Europe. I think it would have great potential! Cheers!

**Comment by corradio** [comment]
Noted, thanks for your input!
