### ISSUE TITLE
Misleading title: map shows CO2 emissions from generation, not consumption

### ISSUE THREAD

**Issue by ipekarik** [tmrowco/electricitymap#491]
I may be getting something wrong, and sorry if it comes across as nitpicking, but this map isn't taking into account actual modes of electricity consumption - it's not comparing the varying CO2 emissions of polluting industries that consume the produced electricity and output CO2 themselves. Therefore, to be more accurate, the title of the project should be "Live CO2 emissions from electricity generation" instead of "Live CO2 emissions of electricity consumption".

**Comment by corradio** [comment]
Good question @ipekarik !
I'm not sure I understand you when you say
> it's not comparing the varying CO2 emissions of polluting industries that consume the produced electricity and output CO2 themselves
We aim at showing the emission tied to the consumption of electricity, as in "how much has been emitted to enable me to consume 1kWh of electricity". The "me" in the previous sentence could refer to an industry that is using electricity, and thus its pollution from the electricity consumption is what we calculate.

If we were to calculate emissions from generation, we wouldn't need to take into account import/exports, because everything produced in a country would be tied to only that country.

**Comment by ipekarik** [comment]
Oh, ok, that actually makes sense now. Thanks for clearing it up!
