### ISSUE TITLE
Encode map location and zoom level in URL

### ISSUE THREAD

**Issue by b2000699** [tmrowco/electricitymap#509]
Hi,

Would be great to encode that in the url, too, so to be able to share e.g. in a conversation about a specific country or region.

Cheers

P.S.: Congratulations for the extension to a global map!

**Comment by Eric-A-Tuttle-1954** [comment]
Is it possible within the project to place Coordinate entry boxes for the user to make an entry?
Then have a pointer indicator for the coordinates to focus upon like a dot.

This would assist in identifying specific wind farm locations so that my group's individuals could place a mouse-over consistently and observe wind speeds for the specific target for the day or time.

I am attempting to provide a data spreadsheet where they can log information in an orderly manner for evidence purposes.

With luck, I hope to provide this spreadsheet to other organizations that are able to extract data in their locations that do not provide public real-time information.

If not, we will have to wing it a bit with approximations of locations that each of us intends to target.
It would also aid in tracking Solar Farm outputs as well. 

Reliability getting a specific location on the map is the objective, though each user would have a different point of interest.

I was hoping that by entering coordinates as shown in the spreadsheet a dot or identification could pop up for the user.

From there they (the users) could place their mouse on the dot and get your windspeed or Solar info from the side.

By entering the coordinates they could return to the exact point of their recording during subsequent visits. 

Please reference the spreadsheet:

[](https://docs.google.com/spreadsheets/u/1/d/e/2PACX-1vR4crq39r9H4gL1GzapRqnZSxNQTAW6WDFJzsCpBasaoZaTUkecZ_ZrOrGxALenLjTeOnIPYAMC0rtR/pubhtml)

**Comment by phillipnunes** [comment]
@b2000699, i did not understand what you mean about map location. When i clicked on a country and copied url, after open it again, the application took me to the country, with their respective information.

[Example](https://www.electricitymap.org/?page=country&solar=false&remote=true&wind=false&countryCode=FI)

Or I misunderstood your suggestion?

The zoom level is not really being encoded in the url.

**Comment by corradio** [comment]
Closing as I don't believe this is a priority
