### ISSUE TITLE
Greece: Islands should be split off from mainland grid

### ISSUE THREAD

**Issue by b2000699** [tmrowco/electricitymap#536]
In Greece multiple islands are not connected to the nation's power grid but produce their own electricity in local oil fired plants (e.g. the island of Paros: https://www.google.gr/maps/@37.1246421,25.2544413,3a,41.4y,22.74h,91.12t/data=!3m6!1e1!3m4!1s9Q7Y0cCk3Q4xPnW9R7TozA!2e0!7i13312!8i6656)

It seems that these oil fired productions are not included in the data of ENTSOE because for Greece there is no oil information stated in electricitymap. But since there is oil production existing, it would be good to indicate this by adding the "?" to the oil indication.

**Comment by Dalius-ENTSO-E** [comment]
Good observation. ENTSO-E TP publish data only for continental part of Greece because this part of the grid is connected to other countries and this is the part where competitive market is operating. Islands are not connected to the continental part of the grid and they are usually small isolated systems. We might add additional data about islands in the future, once TSO or other information aggregator will be ready for this.

**Comment by corradio** [comment]
Thanks for clarifying! I guess we should only color the continental part of Greece then.

**Comment by blackleg** [comment]
It's possible obtain a Greece electricity grid map to see who islands are independent?

**Comment by corradio** [comment]
I think this can help you: https://www.entsoe.eu/map/Pages/default.aspx

**Comment by blackleg** [comment]
@corradio I tried to split Greece's islands but I not found the subunits in the world.json file like the Spain or Portugal islands.

**Comment by corradio** [comment]
Mmh ok, thanks for trying. Will try to take a look when I have time.

**Comment by jarek** [comment]
https://www.entsoe.eu/map/Pages/default.aspx would generally support splitting off mainland, except I'm not sure what these dotted lines should mean:

![image](https://user-images.githubusercontent.com/47415/32347910-82c1286e-c012-11e7-80f3-bfc2ab17c1d8.png)

If these islands are _not_ connected and therefore not reported to ENTSOE, then we can split. Otherwise we will have a problem as those islands are part of a bigger entity in ne_10m_admin_1_states_provinces:

![image](https://user-images.githubusercontent.com/47415/32347950-a763f0e8-c012-11e7-87ce-fc667d561b3d.png)

**Comment by jarek** [comment]
Figured out how the ENTSOE page works... Andros seems connected to mainland at Livadi:

![image](https://user-images.githubusercontent.com/47415/32391173-68b1907a-c0d1-11e7-8a7b-54429bdab25e.png)

But others are only "under construction":

![image](https://user-images.githubusercontent.com/47415/32391054-00f1f45c-c0d1-11e7-8a0c-31f376697bfb.png)

**Comment by jarek** [comment]
If we want to exclude most islands, excluding hasc_codes GR.CR, GR.AS, and GR.AN will get us mostly correct. Mapping individual islands would be a bigger problem, but pragmatically I'm guessing most don't have real-time generation data, so the problem won't come up for a while.
