### ISSUE TITLE
Idea for dealing with small tap targets on mobile

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap#583]
I've been looking at the site on a phone and have ran into the issues with small tap targets Google was complaining about :)

I had an idea on how this could be solved:
- when we're on mobile (or otherwise have viewport size too small):
- define areas with small tap targets. These can be hardcoded for now, I would expect. Off the top of my head, this would currently include Portugal, Northern Ireland, Baltics, an arch from Switzerland through the Balkans to Greece, and Atlantic Canada
- draw a transparent rectangular tap target around the small areas
- layer the tap target above the country layer, disabling the particularly small country targets underneath to keep Google happy
- when the tap target is tapped, zoom into the area into a level where all countries can be reasonably tapped, hide/send the tap target to the background, and reactivate the country targets
- if a suitable zoom level will not be found, draw another tap target rectangle to zoom into a smaller area (e.g. Europe -> central to southern Europe -> Balkans)

Also, #419 would help in the Balkans as currently the exchange arrows take up much of Montenegro's area at closer zoom level.

Also, simply disabling taps for countries where we don't have any information (on mobile) should help, and it won't be quite so hacky as disabling them only for Googlebot.

Unfortunately, I currently don't have the front-end skills to make this happen. But I thought I'd share the idea.

**Comment by corradio** [comment]
Hi @jarek,
Indeed this would be the proper way to do it.
Currently we get the tap layer for "free" because we use SVG. If we really want to speed up the map, we should use canvas, which doesn't come with an interactivity layer.
This would mean we would have to make our own "tap layer", and thus we'd be able to do it the way you suggested it.

I'm closing this however because the small tap target is not currently a problem, but will definitely be addressed when/if we rewrite the map layer in canvas.

Thanks though!
