### ISSUE TITLE
Suggestion : Total power Output and CO2eq t/min map

### ISSUE THREAD

**Issue by Izidir** [tmrowco/electricitymap#618]
First, i've been using this map for some time and you've done a great job.

But when i look at the map (with the overlay labels) and/or select a country, i think it really lack the total power output. They are huge differences among Europe and it doesnt really show up.

And second when selecting a country, one can chose between the power sources or the CO2 emissions for the graph on the left side. It would be great if you could switch the map between gCO2eq/kWh and CO2 emission t CO2eq/min.

Because as up now (2017/07/10 09:30 GMT 0) : 

Poland is at 743 gCO2eq/kWh with a 18,1 GWh total power output
Germany is at 456 gCO2eq/kWh with a 64,5 GWh total power output

But Poland produce 235 t CO2eq/min when Germany produce 511 t CO2eq/min

And on the map Poland show up black and germany some brown orange so germany appear better than poland yet have more than twice the CO2eq emissions...

I don't really know if it belongs here and i don't the ability to make such changes. So if you find this a good idea and someone is willing to take some time to implement i will be happy.

ps : English isn't my motherlangage and i hope eyes won't be bleeding to much while reading.

**Comment by jarek** [comment]
Note however that the population of Poland is less than half of Germany's. (And then you have the edge cases of electricity-heavy industries locating in areas with cheap electricity - this isn't necessarily a bad thing as these are usually fairly environment-friendly nuclear and hydro.)

Total emissions is important, but I think if it is to be shown, it should be shown per capita - otherwise less populated countries will, ceteris paribus, appear "greener".

**Comment by Izidir** [comment]
You're right. I didn't tought of that at first.

**Comment by allocater2** [comment]
A per-capita emission map mode would definitely be more useful then a total emission map mode.

**Comment by corradio** [comment]
Closing this as we don't have plans to do per capita map.
