### ISSUE TITLE
Norway gone?

### ISSUE THREAD

**Issue by teakfi** [tmrowco/electricitymap#629]
Data from Norway seems to be missing. It used to be visible.

**Comment by corradio** [comment]
Yeah it's unfortunately but it comes from ENTSOE (or their dataprovider) not sending the data over.
You can check here:
https://transparency.entsoe.eu/generation/r2/actualGenerationPerProductionType/show?name=&defaultValue=false&viewType=TABLE&areaType=CTY&atch=false&datepicker-day-offset-select-dv-date-from_input=D&dateTime.dateTime=15.07.2017+00:00|CET|DAYTIMERANGE&dateTime.endDateTime=15.07.2017+00:00|CET|DAYTIMERANGE&area.values=CTY|10YNO-0--------C!CTY|10YNO-0--------C&productionType.values=B01&productionType.values=B02&productionType.values=B03&productionType.values=B04&productionType.values=B05&productionType.values=B06&productionType.values=B07&productionType.values=B08&productionType.values=B09&productionType.values=B10&productionType.values=B11&productionType.values=B12&productionType.values=B13&productionType.values=B14&productionType.values=B20&productionType.values=B15&productionType.values=B16&productionType.values=B17&productionType.values=B18&productionType.values=B19&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)

Also, I've seen Norway come and go - sometimes the data is just delayed by half a day, and because our map is real-time, we have to gray out the country :(

I'll have to close this as there's nothing we can do about it. Feel free to re-open if the problem persists.

**Comment by teakfi** [comment]
In that case I'd suggest different colors for countries with data missing from source and countries not implemented.

**Comment by corradio** [comment]
It's a good idea. I think it will be a bit confusing for people not used to the interface.
I'll think about it. Maybe we could show some other type of visual cue.

**Comment by systemcatch** [comment]
Looks like there is live generation data for several countries (including Norway) here.  Might be useful as a backup if ENTSOE is down/slow.
[Live generation](http://www.svk.se/en/national-grid/the-control-room/)

Further market data including hydro storage.
[Market Data](http://www.nordpoolspot.com/Market-data1/Power-system-data/Production1/Production1/ALL1/Hourly1/?view=table)
