### ISSUE TITLE
Data for Bolivia

### ISSUE THREAD

**Issue by igorarduin** [tmrowco/electricitymap#671]
I found hourly production for Bolivia [here](http://www.cndc.bo/media/archivos/graf/gene_hora/gweb_despdia_genera.php). I'll write a parser if nobody is on it!

The installed capacities are declined [here](http://www.cndc.bo/agentes/generacion.php). It's divided in 3 types:
- hydraulic (483.22 MW)
- wind (27 MW)
- thermal (1344.55 MW)

It seems that thermal includes plants consuming gas, oil or biomass. Should I put this overall section as unknown?

**Comment by jarek** [comment]
Good job finding that!

Looks like data for the chart ultimately comes from http://www.cndc.bo/media/archivos/graf/gene_hora/despacho_diario.php?fechag=2017-08-08 which should be alright to parse

The data breakdown is a bit underwhelming, hydro is the only clear one. If we go by the capabilities you've linked, we can probably assume the "intermittent" is wind. Looking through production archive for August 2017, intermittent production has come somewhat close to the specified capacity of 27 MW, but never exceeded it, I saw 18.8 at most.

Watch out because I've seen the intermittent production report -0.01, which breaks data importers (I saw this in data for 2017-08-03). Force the value to be at least 0.

**Comment by jarek** [comment]
http://global-climatescope.org/en/country/bolivia/#/details says installed thermal capacity is mostly gas, with no coal and very limited oil/diesel, however there is about 25% of "other fossil fuels". Probably safest to report the thermal generation as "unknown" when better breakdown is not available.

**Comment by systemcatch** [comment]
@igorarduin Nice work on finding this.  I've been looking at that site and there looks to be detailed programmed generation for the day ahead http://www.cndc.bo/media/archivos/boletindiario/precmp_090817.htm under Programación de la Operación  as well as a detailed report on previous days generation http://www.cndc.bo/media/archivos/boletindiario/dcdr_070817.htm under Resultados de la Operación. 

Since both of those have breakdown by plant maybe we can incorporate it somehow to help provide breakdown of the thermal generation.

**Comment by corradio** [comment]
Maybe we could try to do a breakdown for each generation unit?

![image](https://user-images.githubusercontent.com/1655848/29516752-f4a1563c-8671-11e7-8a65-9fbf82650364.png)

**Comment by igorarduin** [comment]
But won't we need the real time breakdown then? Hourly data are only available for the following variables: "Gen. Prevista", "Gen. Real", "Termo", "Hidro" and "Intermitentes"

**Comment by corradio** [comment]
My bad, I though we had access to the breakdown in real time. My screenshot was only capacities..
Do we access to exchanges? If we don't, I think we can close this issue and perhaps open one very specific for exchanges.

**Comment by igorarduin** [comment]
Nothing on exchanges as far as I know. I realised I did a mistake in my code for the generation forecast function. I am fixing it now and then maybe we could close the issue? Or should I open another one?

**Comment by corradio** [comment]
Just write "Fixes #671" in your pull request, and as soon as the PR gets merged, this issue will automatically be closed.
