### ISSUE TITLE
Improve validation of NI

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#715]
![image](https://user-images.githubusercontent.com/1655848/29720186-066995ea-89b1-11e7-8391-f5019e12b4f7.png)

**Comment by jarek** [comment]
Total production sent from ~500 MW to around 50 MW. Can probably reject any results that have less than 100 MW total production

**Comment by jarek** [comment]
In the parser, I mean.

**Comment by systemcatch** [comment]
Maybe invalidate the datapoint if too many generation types are missing and the production sum is below some floor value (higher than the current one).

**Comment by corradio** [comment]
I think a very simple way is just to verify that hydro is not None.

**Comment by jarek** [comment]
This could have been caught by https://github.com/tmrowco/electricitymap/commit/ef4c909d1c9fd2e470e6c787bd9c2d212a8d3bea if the error criterion was 8x or 5x rather than 10x. 

I am not a fan of looking for specific keys being None. If next time the upstream source reports 1 MW for hydro are we going to make another hardcoded fix?: :/

I still think this is optimally handled by the backend... otherwise we'll have each individual parser implementing their own validator, slightly differently. That won't make for fun maintenance. If you can't compare with past production in the backend, maybe have parsers define an "expected production" value and reference that in zones.json, and have backend discard data that is too different? Or at the very least, have one common validator function in `parsers/lib/`

**Comment by corradio** [comment]
Hey @jarek you are totally right.
I'll work on that during the week. I'll change the error criterion. I however also think that it makes sense to add detailed validation inside each parser, because that's where we have an expectation of what the parser should output.

**Comment by corradio** [comment]
Hi @jarek - just to say this hasn't been forgotten. I'm currently coding a major revamp of the backend to be able to do some big data analytics (there's so much data now!).
As soon as it's done I'll work on this.

**Comment by systemcatch** [comment]
Hi @corradio, I quickly put together a data validator function yesterday.  It could be stored in parsers.lib and called for each individual parser with specific parameters.  I'm sure it could be extended further.

Let me know if it's something you're interested in using.

https://gist.github.com/systemcatch/256b06fca69921c605f0c04a16435255

**Comment by corradio** [comment]
Awesome will take a look and incorporate it

**Comment by systemcatch** [comment]
@corradio 
Cool take a look and let me know.  I'll create a proper branch & PR if it will work.

**Comment by corradio** [comment]
Hi @systemcatch your code looks nice.
I've moved the validation script to the lib folder. The backend automatically validates all datapoints through those functions. We can think about something more elaborate from now on.
This should increase transparency!
