### ISSUE TITLE
Prices on the map

### ISSUE THREAD

**Issue by systemcatch** [tmrowco/electricitymap#744]
Chatting with @corradio on Slack the issue of prices on the map came up.  Basically the prices aren't very useful to visitors due to currency differences, purchasing power and lack of information on taxes etc etc.

One possible idea was to keep prices but move them to the lower graph to show price change over time.  Another was just to remove them completely and make the map simpler.

Any thoughts on this?

**Comment by corradio** [comment]
I've given it a bit more thought. I think people use prices on the EM to:
- Compare the price of electricity between countries, in order to send a Tweet saying X is cheaper than Y, and look at how much more/less it pollutes
- Potentially to look at price variations during a day, but we don't have any graph for this.

I therefore suggest, as @systemcatch puts it, to remove the price from the interface for now.
It might be an idea to show price variations as a graph variation, but I even think this could qualify for the professional version.

@brunolajoie any thoughts?

**Comment by brunolajoie** [comment]
I kinda agree with your idea to remove the prices as long as we don't have a proper split per bidding zones

**Comment by corradio** [comment]
Ok so let's remove the prices then.
