### ISSUE TITLE
AR: 'NoneType' object has no attribute 'getText'

### ISSUE THREAD

**Issue by corradio** [tmrowco/electricitymap#811]
![image](https://user-images.githubusercontent.com/1655848/32265872-43748792-bee5-11e7-8ad3-a1c28c30ae2a.png)

**Comment by systemcatch** [comment]
Does this happen regularly, i.e. same time each day?  My theory is that at midnight (AR time) that page element disappears until 1am.

**Comment by corradio** [comment]
Might be:

[image: Inline image 1]

**Comment by systemcatch** [comment]
I setup crontab to run the parser every 5 minutes and log everything, then let it run in the background all night.  Checking the logs today there's some weird behavior going on.  All times are AR timezone.

11.10pm - Raises error.
Runs fine until.......
12pm - 2.20pm - Fails continuously with error.

The kicker is that when I look at the page grab from each failed run it's not that the page element from find_hour is missing.  No the actual problem is the entire application that generates the data looks like it's shutdown/unavailable!  I will keep running the parser tonight and see if the pattern repeats.

Looking at the overall data application structure it's very cobbled together.  We may need to find ways to work around this.

**Comment by corradio** [comment]
When you say "shutdown/unavailable", what do you mean exactly?
Maybe it's a good idea to log the HTTP code and the resulting HTML in order
to produce a better error.

Thanks for investigating

**Comment by systemcatch** [comment]
From what I can see the page is still accessible, but the application that hosts the data is offline.  I'll incorporate your suggestions and see if we can get a better html grab and status code.

**Comment by systemcatch** [comment]
Didn't manage to get an error code but this is a screenshot of the page when it was failing.
![ar_screenshot](https://user-images.githubusercontent.com/30196510/32542355-35efd98e-c46a-11e7-9b11-370ee1f9a69d.png)
Looks like the application hosted on the page is down.

**Comment by systemcatch** [comment]
After monitoring this for a few days there is not really a consistent pattern with the downtime.  Last night the application was only down on/off for around 30mins total.  Based on the fact that the whole data setup is somewhat hacked together I don't think there is much we can do here.  I'll close this for now but feel free to reopen if anything else happens.

**Comment by corradio** [comment]
Thanks for looking into this.
