### ISSUE TITLE
Base load vs peak load in power generation chart

### ISSUE THREAD

**Issue by rcrug** [tmrowco/electricitymap#845]
The brand new graph gets a little bit messy as solar/eolic changes during the day, gas/hydro changes to follow the load and eventually prevent lack of solar/eolic, while coal/nuclear/oil stays almost constant during the day. An example (Spain)
![immagine](https://user-images.githubusercontent.com/33553278/32670850-5e47ebec-c645-11e7-8681-d1bf6d202124.png)

So a more readable graph would result with (from the bottom):
-nuclear
-coal
-oil
-hydro
-gas
-eolic
-solar

**Comment by corradio** [comment]
Hi @rcrug,

We've tried that, but found out that showing the least controllable load at the bottom makes more sense, simply because it highlights how the fossil (and imports) change to fill the rest of the space left out between the intermittent renewable and the total demand.
Putting the base load at the bottom makes it hard to see the (non-controllable) variation in intermittent renewable.

The main idea to convey is that intermittent renewable are what you start with, then you "fill" the rest of the gap with either fossil / base load, then imports.
