### ISSUE TITLE
Bornholm

### ISSUE THREAD

**Issue by jarek** [tmrowco/electricitymap#882]
From the nitpicking file ;)

Currently we draw Bornholm as part of Denmark.

From what I've read, Bornholm is connected to Swedish mainland grid ([Bornholm Cable](https://en.wikipedia.org/wiki/Bornholm_Cable)).

Questions/issues:
- [ ] Is Bornholm generation included in Swedish or Danish totals, or neither?
- [ ] Is it possible to break out its generation, including any imports/exports?

**Comment by Bjarkigd** [comment]
In sorta the same area, Shetland is not connected to the main UK Grid, but is drawn as being part of it.

**Comment by jarek** [comment]
@bjarkigd right, good point! I pasted that into the ticket for Scotland, #596

**Comment by corradio** [comment]
Hi @jarek,
Happy to see you added this issue. I'm in discussion with DTU Elektro and Bornholm to try to get us access to the data. It's taking time though, but I know they have it!
Will send them a follow up email
Olivier

**Comment by corradio** [comment]
Here's some info:
- Live viz is here: http://bornholm.powerlab.dk/
- Live data is here (JSON): http://bornholm.powerlab.dk/visualizer/latestdata, including interconnector to SE
- Apparently the data we get for DK currently includes Bornholm production (same with interconnectors)

Let's do it!

**Comment by corradio** [comment]
I've added the geometry. Only the parser is left to do.

**Comment by systemcatch** [comment]
What sort of generation is factory?

**Comment by corradio** [comment]
Biomass

**Comment by alixunderplatz** [comment]
@systemcatch from looking at the dashboard, I'd say Biomass
" The important CHP plant in Rønne has just been converted from coal to sustainable biomass, so most of the electricity consumption of approx. 230 GWh will be covered with green electricity. "

**Comment by corradio** [comment]
@systemcatch are you working on this? If yes, can you assign yourself? Then we can see who is working on what!

**Comment by systemcatch** [comment]
Not at the moment but I can do it if you want to get this up and running
soon? Maybe someone else would like a crack at it though, looks like a good
first issue.

On 26 Jan 2018 16:05, "Olivier Corradi" <notifications@github.com> wrote:

@systemcatch <https://github.com/systemcatch> are you working on this? If
yes, can you assign yourself? Then we can see who is working on what!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tmrowco/electricitymap/issues/882#issuecomment-360826316>,
or mute the thread
