### ISSUE TITLE
Italy is missing from ENTSOE

### ISSUE THREAD

**Issue by systemcatch** [tmrowco/electricitymap#930]
As per the title there has been no data for Italy on ENTSOE for at least 2-3 weeks.

@Dalius-ENTSO-E any news on this?

**Comment by systemcatch** [comment]
Italy is back now!

**Comment by frafra** [comment]
Great!
What is "unknown source"? It looks like it could be just a sum of imported energy power. If that is the case I suppose it should be hidden/remove.

**Comment by alixunderplatz** [comment]
@frafra As far as I know, the "unknown" part is generation from thermal power plants, but it's hard to divide them into gas and coal. It is also reported to entso-e as "other".
![image](https://user-images.githubusercontent.com/25743609/34773126-da7055e8-f60a-11e7-9509-3ae9ec016f05.png)

**Comment by brunolajoie** [comment]
Good catch, it's indeed likely to be a mix of thermal power, but we don't have the breakdown from ENTSOE. What we could try to do is:
- find another real time data source with better breakdown
or if not available in real time
- what's the most likely statistical breakdown in this "unknown" category based on historical data, in order to update the estimated carbon intensity of "unknown".
![image](https://user-images.githubusercontent.com/22095643/34788652-88ac9d1c-f63b-11e7-8d9b-d9d9d8cba904.png)
