### ISSUE TITLE
Change source for Data in Germany

### ISSUE THREAD

**Issue by Bohne13** [tmrowco/electricitymap#989]
I'm not sure if it's an improvement to the German data source. But could someone check the data source from Frauenhofer ISE?

https://www.energy-charts.de/price_de.htm

**Comment by systemcatch** [comment]
Thanks for the link @Bohne13!

https://www.energy-charts.de/power.htm?source=all-sources&week=2&year=2018 looks quite good, hourly detailed breakdown by type for the current day. And we can get past breakdown as well.

@corradio we talked once about having multiple parsers per zone, maybe that would work here?  It could be used as a backup if ENTSOE goes down, or it could run in the background permanently to augment the dataset.

**Comment by alixunderplatz** [comment]
More details regarding sources for Germany as sort of a summary: 
(if this hasn't been said before or for people who didn't know the data sources yet)

**Energy Charts** by Bruno Burger / Fraunhofer ISE is probably the "most famous" source for all types of info on the German electricity market. They use data from the 4 TSOs and the EEX / EPEX SPOT, sometimes maybe correction factors are used to cover the entire generation, not too sure about that.
Last year, about 550 TWh of German **net** generation were covered by the tracking of Energy Charts. Gross generation and some industry generation are missing, so the data is very close to what really comes out of the socket in your wall. 
I've been following this site and the new features since the start of its existence and was really happy to see this info well visualized and aggregated.

There also is a map of all of the reporting/known power plants / units: 
https://energy-charts.de/osm_de.htm#

Per-unit generation is published after (~) 5 days - one could split this and distribute it to the TSO-areas.
They seem to take this from EEX. But that is also available on entso-e.
 
![image](https://user-images.githubusercontent.com/25743609/34687151-2ec4c448-f4ae-11e7-9d5a-b9c049180b9f.png)

Something else of interest might be the (specific) emissions of German coal power plants (related to #960 #738):

![image](https://user-images.githubusercontent.com/25743609/34688085-352a6e66-f4b1-11e7-80ed-d33cb100b02d.png)

- - -

On this occasion, check out the **Agorameter**, too! 

It is published by "Agora Energiewende", a think tank on the energy transition. The data is including correction factors based on seasonal and yearly generation data. I met these people in person - if any questions related to their site and tool may occur, I may contact them.

https://www.agora-energiewende.de/de/themen/-agothem-/Produkt/produkt/76/Agorameter/
![image](https://user-images.githubusercontent.com/25743609/34686944-7ef27588-f4ad-11e7-9d82-27d5ef34d970.png)

This is the documentation:
https://www.agora-energiewende.de/en/topics/-agothem-/Produkt/produkt/180/Agorameter+-+Dokumentation/

- - -

Of course, since they are reporting to entso-e, **the four German TSOs** are an additional source for real time generation and exchanges, too.
TSO 50Hertz has a bunch of very detailed data on their website. You can also find data of the other three TSOs Amprion, TenneT and TransnetBW. Splitting Germany into four zones is possible!

**Comment by corradio** [comment]
Can I close this one as I don't believe we're going to change data source?

**Comment by brunolajoie** [comment]
Yes sure, the discussion is shifting to #1216, we'll close this one and keep it for later reference!
